### ISSUE TITLE
MonstersInCell unhandled exception

### ISSUE THREAD

**Issue by violin-suzutsuki** [GentleGanku/GrimliteRev#14]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Grimoire.Game.World.MonstersInCell(String cell)
   at Grimoire.Botting.OptionsManager.<Provoke>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by GentleGanku** [comment]
This is fixed on the new update, please check again.
